### ISSUE TITLE
Router/index.js 수정 필요

### ISSUE THREAD

**Issue by LeeSeongJinCa** [dsm-pear/user_frontend#21]
https://github.com/DSM-PEAR/user_frontend/blob/12300540d8b3c5c465d804fa307e9f505af75aa0/src/Routers/index.js#L1-L3

Router안에 있는 index.js 인데
Components를 export할 이유가 없어보입니다.

이거 pr날릴 때 말했어야 했는데... merge가 되었네요.
approve한 사람 누굽니까!

**Comment by silverbeen** [comment]
죄송합니답.. 접니답.. ㅠㅠ
